---
blank_issues_enabled: false
contact_links:
  - name: LyngdorfBrowser Community Support
    url: https://github.com/michaelmsonne/LyngdorfBrowser/discussions
    about: Please ask and answer questions here.
